version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: berotrac-api-dev

    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_started

    volumes:
      - .:/app
      - /app/node_modules

    command: npm run dev

    networks:
      - berotrac-network

  postgres:
    image: postgres:17-alpine

    container_name: berotrac-db-dev

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: berotrac

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - berotrac-network

  redis:
    image: redis:8-alpine

    container_name: berotrac-redis-dev

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - berotrac-network

networks:
  berotrac-network:

volumes:
  postgres_data:
  redis_data: